using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using InterpreterModules.interpreter;

/// <summary>
/// Custom visitor for COBOL parse trees that extends the base visitor generated by ANTLR.
/// </summary>
public class CustomVisitor : cobolBaseVisitor<object> 
{
    private Dictionary<string, Value> _valueHashMap = new Dictionary<string, Value>();
    public override object VisitDisplay([NotNull] cobolParser.DisplayContext context)
    {
        int len = context.withnoadvancing() == null ? context.ChildCount : context.ChildCount - 1;
        for (int i = 1; i < len; i++)
        {
            Console.WriteLine(context.GetChild(i).GetText());
        }
        if (context.withnoadvancing == null){
            Console.WriteLine("\n");
        }
        return DefaultResult;
    }
    //Problem for now is that i dnot understand how to fill _valueHashMap. it is actuallu null
    //and when trying to get a value from _hashmap we get an object with a null reference
    public override object VisitAdd([NotNull] cobolParser.AddContext context)
    {
        string key;
        key = context.giving() is null ?
            context.identifiers().GetText() : context.giving().identifiers().GetText();

        Value value;
        _valueHashMap.TryGetValue(key, out value);
        try
        {
            if (!value.IsNumerical())
                throw new Exception("Value is not numerical");
        }
        catch(NullReferenceException ex)
        {
            throw new Exception("VisitAdd: Value is null");
        }

        int newValue;
        if (context.giving() is not null)
        {
            //Potential problem with BASE
            newValue = int.Parse(context.GetText().Trim());
        }
        else
        {
            if (value.Val is null)
                newValue = 0;
            else
                newValue = int.Parse(value.Val);
        }

        for(int i = 0; i < context._additions.Count; i++)
        {
            //Potential problems with Text property
            newValue += Int32.Parse(
                context._additions[i].Text.Trim()
                );
        }

        value.AssignValue(newValue.ToString());
        _valueHashMap.Add(key, value);

        return DefaultResult;
    }
}