//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from cobol.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IcobolListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class cobolBaseListener : IcobolListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] cobolParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] cobolParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.identification_division"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentification_division([NotNull] cobolParser.Identification_divisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.identification_division"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentification_division([NotNull] cobolParser.Identification_divisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.data_division"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_division([NotNull] cobolParser.Data_divisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.data_division"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_division([NotNull] cobolParser.Data_divisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.picture"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPicture([NotNull] cobolParser.PictureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.picture"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPicture([NotNull] cobolParser.PictureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.like"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLike([NotNull] cobolParser.LikeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.like"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLike([NotNull] cobolParser.LikeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.procedure_division"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure_division([NotNull] cobolParser.Procedure_divisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.procedure_division"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure_division([NotNull] cobolParser.Procedure_divisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.using"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsing([NotNull] cobolParser.UsingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.using"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsing([NotNull] cobolParser.UsingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.use"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUse([NotNull] cobolParser.UseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.use"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUse([NotNull] cobolParser.UseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.sentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentence([NotNull] cobolParser.SentenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.sentence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentence([NotNull] cobolParser.SentenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] cobolParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] cobolParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.display"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplay([NotNull] cobolParser.DisplayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.display"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplay([NotNull] cobolParser.DisplayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.withnoadvancing"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithnoadvancing([NotNull] cobolParser.WithnoadvancingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.withnoadvancing"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithnoadvancing([NotNull] cobolParser.WithnoadvancingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.atomic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomic([NotNull] cobolParser.AtomicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.atomic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomic([NotNull] cobolParser.AtomicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="cobolParser.identifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifiers([NotNull] cobolParser.IdentifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="cobolParser.identifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifiers([NotNull] cobolParser.IdentifiersContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
